apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: mongodb
          image: mongo:4
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          readinessProbe:
            tcpSocket:
              port: 27017
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 27017
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          volumeMounts:
          - mountPath: /data/db
            name: mongodb-data
      volumes:
        - emptyDir:
            medium: ""
          name: mongodb-data